#!/usr/bin/env node

"use strict";


var c = require('skilstak-colors')

var printColors = function (message) {
  console.log(c.rc()  +   message);
  console.log(c.rc() +  "SENSEI FUZZY BUNS IS UNCOOL:}");
  console.log(c.rc() +  "Hello World");
  console.log(c.rc() +  "MR.JACKSON IS A PIE FACE:}");
}  
 
var printGreen = function (message) { 
  console.log(c.rc() +  "WHAT ARE THOSE. MY SHOES!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
  console.log(c.rc() +  "Mr.JaJa does not know the color of the rainbow. Do you?");
  console.log(c.rc() +  message);            
  console.log(c.rc() +  "I caught ben on his phone.... then i got 10 skil bux");
}

var firstValue = process.argv[2];
var name = "World";
var option = "-g";

if (firstValue[0] === "-") {
  option = firstValue;
  console.log(option)
}
if (option === "-g") {
  printGreen(name);
}

