#!/usr/bin/env node

"use strict";


var c = require('skilstak-colors')

var printColors = function (message) {
  console.log(c.rc() +   message);
  console.log(c.rc() +  " HELLO WORLD");
  console.log(c.rc() +  "luke i am your father");
  console.log(c.rc() +   "really!");
  console.log(c.rc() +  "no i am just a creepy old actor");
  console.log(c.rc() +  "lets just get back to the script");
  console.log(c.rc() +  "but, but your in our family tree");            
  console.log(c.rc() +  "oh yeah i forgot");
}

var printColors = function (message) {
}



var firstValue = process.argv[2];
console.log(firstValue);

